name: Automatic Docker Image Publish

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    - uses: actions/checkout@v4

    - name: Install modules
      run: pnpm install

    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx

    # - name: install node v12
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 12

    # - name: pnpm install
    #   run: pnpm install

    # - name: tsc
    #   uses: icrawl/action-tsc@v1